### PR TITLE
Fix for NewHorizons/#1747 (library part)

### PR DESCRIPTION
**Pull request by OneEyeMaker**
@Dream-Master @Namikon 
I made that for you.

P. S. Please, check syntax and test.

### CODE REVIEW

**Comment by OneEyeMaker** [comment]
@Dream-Master @Namikon 
Everything is tested and works fine!
Merge, please...

**Comment by Namikon** [comment]
I have rewritten that part of YAMCore already, but I have no functional Computer at the moment to build/push/update it. Still fixing bugs with my build

**Comment by Dream-Master** [comment]
@Namikon are yo able to push your changes to git or did we merge OneEyeMakers changes?

**Comment by Namikon** [comment]
@Dream-Master I could but I have no way to verify my changes, as they involve changes in CoreMod, just like the proposed changes here. Mine and these changes here are not compatible at all, they follow a completely different approach.

**Comment by Dream-Master** [comment]
@Namikon if you have spare time on the weekend i can test if you said me what i have to test if this help. (or voicechat)

**Comment by Dream-Master** [comment]
fixed

**Pull request closed without merging**
